---
- hosts: localhost

  vars:
    folder : "/{{ vcenter.datacenter }}/vm/openshift/{{ config.clusterName }}"
    datastore: "{{ vcenter.datastore }}"
    govc_file: "/usr/local/bin/govc"
    hostname: helper
  vars_files:
    - "./vars/vars-{{ BUILD_LAB }}.yml"

  tasks:

    - name: VMSETUP 1.0 | Destroy Helper Node
      vmware_guest:
        hostname: "{{ vcenter.ip }}"
        username: "{{ vcenter.username }}"
        password: "{{ vcenter.password }}"
        datacenter: "{{ vcenter.datacenter }}"
        cluster: "{{ vcenter.cluster }}"
        validate_certs: no
        folder: "{{ folder }}"
        name: "{{ hostname }}.{{ config.baseDomain }}"
        state: absent
        force: yes
        template: "rhel7.7-template"
        disk:
        - size_gb: 30
          type: thin
          datastore: "{{ datastore }}"
      register: helpernode
      tags:
        - "1"

    - name: VMSETUP 2.0 | VMware Cluster Folder Remove
      vcenter_folder:
        hostname: "{{ vcenter.ip}}"
        username: "{{ vcenter.username }}"
        password: "{{ vcenter.password }}"
        datacenter_name: "{{ vcenter.datacenter }}"
        validate_certs: no
        parent_folder: "openshift"
        folder_name: "{{ config.clusterName }}"
        folder_type: vm
        state: absent
      ignore_errors: true
      tags:
        - "1"