---
- hosts: localhost
  vars: 
    bootstrapContent : "{{ lookup('file', '{{ playbook_dir }}/install-dir/append-bootstrap.64') }}"
    masterContent : "{{ lookup('file', '{{ playbook_dir }}/install-dir/master.64') }}"
    workerContent : "{{ lookup('file', '{{ playbook_dir }}/install-dir/worker.64') }}"
    templateName : rhcos-4.3.0-x86_64-vmware
    folder : "/{{ vcenter.datacenter }}/vm/{{ config.clusterName }}"
    datastore: "{{ vcenter.datastore }}"
    govc_file: "/usr/local/bin/govc"
  tasks:
    - name: "Bootstrap base64"
      debug:
        msg: "{{ bootstrapContent }}" 
    - name: "Master base64"
      debug:
        msg: "{{ masterContent }}" 
    - name: "Worker base64 "
      debug:
        msg: "{{ workerContent }}" 
    - name: Create bootstrap VM from the template
      vmware_guest:
        hostname: "{{ vcenter.ip }}"
        username: "{{ vcenter.username }}"
        password: "{{ vcenter.password }}"
        datacenter: "{{ vcenter.datacenter }}"
        cluster: "{{ vcenter.cluster }}"
        validate_certs: no
        folder: "{{ folder }}"
        name: bootstrap
        state: poweredoff
        template: "{{ templateName }}"
        disk:
        - size_gb: 16 
          type: thin
          datastore: "{{ datastore }}"
        hardware:
          memory_mb: 8192 
          num_cpus: 4
          memory_reservation_lock: True
        networks:
        - name: "{{ vcenter.vm_network }}"
        wait_for_ip_address: no 
        customvalues:
          - key: guestinfo.ignition.config.data
            value: "{{ bootstrapContent }}"
          - key: guestinfo.ignition.config.data.encoding
            value: base64
          - key: disk.EnableUUID
            value: "TRUE"
    - name: Create master VMs from ther template
      vmware_guest:
        hostname: "{{ vcenter.ip }}"
        username: "{{ vcenter.username }}"
        password: "{{ vcenter.password }}"
        datacenter: "{{ vcenter.datacenter }}"
        cluster: "{{ vcenter.cluster }}"
        validate_certs: no
        folder: "{{ folder }}"
        name: "{{ item.name }}"
        state: poweredoff
        template: "{{ item.template }}"
        disk:
        - size_gb: 16
          type: thin
          datastore: "{{ datastore }}" 
        hardware:
          memory_mb: 12288
          num_cpus: 4
          memory_reservation_lock: True
        networks:
        - name: "{{ vcenter.vm_network }}"
        wait_for_ip_address: no
        customvalues:
         - key: guestinfo.ignition.config.data
           value: "{{ masterContent }}"
         - key: guestinfo.ignition.config.data.encoding
           value: base64
         - key: disk.EnableUUID
           value: "TRUE"
      loop:
        - { name : "master0", template: "{{ templateName }}" }
        - { name : "master1", template: "{{ templateName }}" }
        - { name : "master2", template: "{{ templateName }}" }

    - name: Create worked VMs from the template
      vmware_guest:
        hostname: "{{ vcenter.ip }}"
        username: "{{ vcenter.username }}"
        password: "{{ vcenter.password }}"
        datacenter: "{{ vcenter.datacenter }}"
        cluster: "{{ vcenter.cluster }}"
        validate_certs: no
        folder: "{{ folder }}"
        name: "{{ item.name }}"
        state: poweredoff
        template: "{{ item.template }}"
        disk:
        - size_gb: 16
          type: thin
          datastore: "{{ datastore }}"
        hardware:
          memory_mb: 8192
          num_cpus: 4
          memory_reservation_lock: True
        networks:
        - name: "{{ vcenter.vm_network }}"
        wait_for_ip_address: no
        customvalues:
         - key: guestinfo.ignition.config.data
           value: "{{ workerContent }}"
         - key: guestinfo.ignition.config.data.encoding
           value: base64
         - key: disk.EnableUUID
           value: "TRUE"
      loop:
        - { name : "worker0", template: "{{ templateName }}" }
        #- { name : "worker1", template: "worker1-template" }
        #- { name : "worker2", template: "worker2-template" }
        

    - name: Update Mac Address
      command: "{{ govc_file }} vm.network.change -net.address {{ item.mac }} -vm={{ item.name }} ethernet-0"
      environment:
        GOVC_HOST: "{{ vcenter.ip }}"
        GOVC_URL: "https://{{ vcenter.ip }}/sdk"
        GOVC_USERNAME: "{{ vcenter.username }}"
        GOVC_PASSWORD: "{{ vcenter.password }}"
        GOVC_INSECURE: 1
        GOVC_DATASTORE: "{{ vcenter.datastore }}"
        GOVC_DATACENTER: "{{ vcenter.datacenter }}"
        GOVC_CLUSTER: "{{ vcenter.cluster }}"
      loop:
        - { name : "bootstrap", mac: "{{ config.bootstrapmac }}" }
        - { name : "master0", mac: "{{ config.master0mac }}" }
        - { name : "master1", mac: "{{ config.master1mac }}" }
        - { name : "master2", mac: "{{ config.master2mac }}" }
        - { name : "worker0", mac: "{{ config.worker0mac }}" }
#        - { name : "worker1", mac: "{{ config.worker1mac }}" }
#        - { name : "worker2", mac: "{{ config.worker2mac }}" }
      retries: 3
      delay: 3
      register: result
      until: result.rc == 0

    - name: Update CPU latencySensitivity
      command: "{{ govc_file }} vm.change -vm={{ item.name }} -e sched.cpu.latencySensitivity=high"
      environment:
        GOVC_HOST: "{{ vcenter.ip }}"
        GOVC_URL: "https://{{ vcenter.ip }}/sdk"
        GOVC_USERNAME: "{{ vcenter.username }}"
        GOVC_PASSWORD: "{{ vcenter.password }}"
        GOVC_INSECURE: 1
        GOVC_DATASTORE: "{{ vcenter.datastore }}"
        GOVC_DATACENTER: "{{ vcenter.datacenter }}"
        GOVC_CLUSTER: "{{ vcenter.cluster }}"
      loop:
        - { name : "bootstrap" }
        - { name : "master0" }
        - { name : "master1" } 
        - { name : "master2" }
        - { name : "worker0" }
      retries: 3
      delay: 3
      register: result
      until: result.rc == 0

    - name: Start all VM's
      vmware_guest:
        hostname: "{{ vcenter.ip }}"
        username: "{{ vcenter.username }}"
        password: "{{ vcenter.password }}"
        datacenter: "{{ vcenter.datacenter }}"
        validate_certs: no
        folder: "{{ folder }}"
        name: "{{ item.name }}"
        state: poweredon
      loop:
        - { name : "bootstrap" }
        - { name : "master0" }
        - { name : "master1" }
        - { name : "master2" }
        - { name : "worker0" }
...
