apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
 name: image-registry-storage
spec: 
 storageClassName: "ocs-storagecluster-cephfs"
 accessModes: 
  - 
   ReadWriteMany
 resources: 
  requests: 
   storage: 10Gi
