apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: ClusterLogging.v1.logging.openshift.io,Collector.v1alpha1.logging.openshift.io,LogForwarding.v1alpha1.logging.openshift.io
  generateName: openshift-logging-
  namespace: openshift-logging
spec:
  targetNamespaces:
  - openshift-logging
